// <auto-generated />
using System;
using ImportExport.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImportExport.Infrastructure.Migrations
{
    [DbContext(typeof(ImportExportDbContext))]
    [Migration("20260303152806_InitialImportExport")]
    partial class InitialImportExport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("importexport")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImportExport.Domain.Profiles.MappingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EntityTypeName");

                    b.ToTable("MappingProfiles", "importexport");
                });

            modelBuilder.Entity("ImportExport.Domain.Profiles.MappingProfile", b =>
                {
                    b.OwnsMany("ImportExport.Domain.Profiles.MappingFieldRule", "FieldRules", b1 =>
                        {
                            b1.Property<Guid>("MappingProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("SourceColumn")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("TargetField")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("TransformHint")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("MappingProfileId", "Id");

                            b1.ToTable("MappingProfiles", "importexport");

                            b1.ToJson("FieldRules");

                            b1.WithOwner()
                                .HasForeignKey("MappingProfileId");
                        });

                    b.Navigation("FieldRules");
                });
#pragma warning restore 612, 618
        }
    }
}
