// <auto-generated />
using System;
using Measures.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Measures.Infrastructure.Migrations
{
    [DbContext(typeof(MeasuresDbContext))]
    [Migration("20260302123226_InitMeasures")]
    partial class InitMeasures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("measures")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Measures.Domain.Measures.Measure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ConfDataQuality")
                        .HasColumnType("integer");

                    b.Property<int>("ConfDataRecency")
                        .HasColumnType("integer");

                    b.Property<int>("ConfDataSourceCount")
                        .HasColumnType("integer");

                    b.Property<int>("ConfSpecificity")
                        .HasColumnType("integer");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dependencies")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("EffortHours")
                        .HasColumnType("double precision");

                    b.Property<double>("GraphCostEfficiency")
                        .HasColumnType("double precision");

                    b.Property<int>("GraphDependentsCount")
                        .HasColumnType("integer");

                    b.Property<double>("GraphImpactMultiplier")
                        .HasColumnType("double precision");

                    b.Property<decimal>("GraphTotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ImpactRisk")
                        .HasColumnType("integer");

                    b.Property<string>("IsoId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Justification")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("IsoId", "UserId")
                        .IsUnique();

                    b.ToTable("Measures", "measures");
                });

            modelBuilder.Entity("SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn")
                        .HasDatabaseName("IX_measures_OutboxMessages_ProcessedOn")
                        .HasFilter("\"ProcessedOn\" IS NULL");

                    b.ToTable("OutboxMessages", "measures");
                });
#pragma warning restore 612, 618
        }
    }
}
